spring:
  application:
    name: api_auth

  datasource:
    url: jdbc:h2:mem:apiauth_db
    driverClassName: org.h2.driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    h2:
      console:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 2592000000


login:
  level:
    ma:
      bookmanagement:
        security: DEBUG
    org:
      springframework:
        security: DEBUG